# Generated by Django 5.0 on 2024-06-10 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('access', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='face',
            name='userid',
        ),
        migrations.AddField(
            model_name='face',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myprojectapp.user'),
        ),
    ]
