# Generated by Django 5.0 on 2024-06-30 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0002_user_remove_face_userid_face_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntryExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('door', models.CharField(max_length=100)),
                ('entryexit', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myprojectapp.user')),
            ],
        ),
    ]
