# Generated by Django 4.2.9 on 2024-07-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0003_userentryexit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentryexit',
            name='door',
            field=models.CharField(max_length=255),
        ),
    ]
